// <auto-generated />
using System;
using Cahut_Backend.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CahutBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cahut_Backend.Models.Chat", b =>
                {
                    b.Property<Guid>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumOfMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid>("PresentationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ChatId");

                    b.HasIndex("PresentationId")
                        .IsUnique();

                    b.ToTable("Chat", (string)null);
                });

            modelBuilder.Entity("Cahut_Backend.Models.ChatMessage", b =>
                {
                    b.Property<Guid>("ChatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimeSend")
                        .HasColumnType("datetime2");

                    b.Property<string>("MsgContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChatId", "TimeSend");

                    b.HasIndex("ChatId");

                    b.HasIndex("TimeSend");

                    b.ToTable("ChatMessage", (string)null);
                });

            modelBuilder.Entity("Cahut_Backend.Models.EmailSender", b =>
                {
                    b.Property<string>("usr")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EmailSended")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("pwd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("usr");

                    b.ToTable("EmailSender", (string)null);
                });

            modelBuilder.Entity("Cahut_Backend.Models.Group", b =>
                {
                    b.Property<Guid>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("HasPresentationPresenting")
                        .HasColumnType("bit");

                    b.Property<string>("JoinGrString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumOfMems")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PresentationId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroupId");

                    b.HasIndex("GroupName")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.ToTable("Group", (string)null);
                });

            modelBuilder.Entity("Cahut_Backend.Models.GroupDetail", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("JoinedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("GroupId", "MemberId");

                    b.HasIndex("GroupId");

                    b.HasIndex("MemberId");

                    b.HasIndex("RoleId");

                    b.ToTable("GroupDetail", (string)null);
                });

            modelBuilder.Entity("Cahut_Backend.Models.MultipleChoiceOption", b =>
                {
                    b.Property<string>("OptionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumSelected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("OptionContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("OptionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("MultipleChoiceOption", (string)null);
                });

            modelBuilder.Entity("Cahut_Backend.Models.Presentation", b =>
                {
                    b.Property<Guid>("PresentationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBeingPresented")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PresentationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PresentationType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PresentationId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Presentation", (string)null);
                });

            modelBuilder.Entity("Cahut_Backend.Models.PresentationDetail", b =>
                {
                    b.Property<Guid>("PresentationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ColaboratorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PresentationId", "ColaboratorId");

                    b.HasIndex("PresentationId");

                    b.ToTable("PresentationDetail", (string)null);
                });

            modelBuilder.Entity("Cahut_Backend.Models.Question", b =>
                {
                    b.Property<string>("QuestionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Cahut_Backend.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("Cahut_Backend.Models.Slide", b =>
                {
                    b.Property<string>("SlideId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsCurrent")
                        .HasColumnType("int");

                    b.Property<Guid>("PresentationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SlideOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("SlideType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SlideId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Cahut_Backend.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccountStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiredTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2023, 1, 2, 16, 49, 41, 359, DateTimeKind.Utc).AddTicks(7869));

                    b.Property<string>("ResetPasswordString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Cahut_Backend.Models.UserSubmitChoice", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OptionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("QuestionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SubmitTime")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "OptionId", "QuestionId");

                    b.HasIndex("GroupId");

                    b.HasIndex("OptionId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSubmitChoice", (string)null);
                });

            modelBuilder.Entity("Cahut_Backend.Models.UserUpvoteQuestion", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PresentationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QuestionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimeUpVote")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "PresentationId", "QuestionId");

                    b.HasIndex("GroupId");

                    b.HasIndex("PresentationId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserUpvoteQuestion", (string)null);
                });

            modelBuilder.Entity("Cahut_Backend.Models.MultipleChoiceQuestion", b =>
                {
                    b.HasBaseType("Cahut_Backend.Models.Question");

                    b.Property<string>("RightAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SlideId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("SlideId");

                    b.ToTable("MultipleChoiceQuestion", (string)null);
                });

            modelBuilder.Entity("Cahut_Backend.Models.PresentationQuestion", b =>
                {
                    b.HasBaseType("Cahut_Backend.Models.Question");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumUpVote")
                        .HasColumnType("int");

                    b.Property<Guid>("PresentationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isAnswered")
                        .HasColumnType("bit");

                    b.HasIndex("PresentationId");

                    b.ToTable("PresentationQuestion", (string)null);
                });

            modelBuilder.Entity("Cahut_Backend.Models.HeadingSlide", b =>
                {
                    b.HasBaseType("Cahut_Backend.Models.Slide");

                    b.Property<string>("HeadingContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubHeadingContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("PresentationId");

                    b.ToTable("HeadingSlide", (string)null);
                });

            modelBuilder.Entity("Cahut_Backend.Models.MultipleChoiceSlide", b =>
                {
                    b.HasBaseType("Cahut_Backend.Models.Slide");

                    b.Property<int>("NumOfMultipleChoiceQuestion")
                        .HasColumnType("int");

                    b.HasIndex("PresentationId");

                    b.ToTable("MultipleChoiceSlide", (string)null);
                });

            modelBuilder.Entity("Cahut_Backend.Models.ParagraphSlide", b =>
                {
                    b.HasBaseType("Cahut_Backend.Models.Slide");

                    b.Property<string>("HeadingContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParagraphContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("PresentationId");

                    b.ToTable("ParagraphSlide", (string)null);
                });

            modelBuilder.Entity("Cahut_Backend.Models.Chat", b =>
                {
                    b.HasOne("Cahut_Backend.Models.Presentation", "Presentation")
                        .WithOne("Chat")
                        .HasForeignKey("Cahut_Backend.Models.Chat", "PresentationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Presentation");
                });

            modelBuilder.Entity("Cahut_Backend.Models.ChatMessage", b =>
                {
                    b.HasOne("Cahut_Backend.Models.Chat", "Chat")
                        .WithMany("ChatMessages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("Cahut_Backend.Models.Group", b =>
                {
                    b.HasOne("Cahut_Backend.Models.User", "User")
                        .WithMany("Group")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cahut_Backend.Models.GroupDetail", b =>
                {
                    b.HasOne("Cahut_Backend.Models.Group", "Group")
                        .WithMany("GroupDetails")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cahut_Backend.Models.Role", "Role")
                        .WithMany("GroupDetails")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Cahut_Backend.Models.MultipleChoiceOption", b =>
                {
                    b.HasOne("Cahut_Backend.Models.MultipleChoiceQuestion", "MultipleChoiceQuestion")
                        .WithMany("MultipleChoiceOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MultipleChoiceQuestion");
                });

            modelBuilder.Entity("Cahut_Backend.Models.Presentation", b =>
                {
                    b.HasOne("Cahut_Backend.Models.User", "User")
                        .WithMany("Presentations")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cahut_Backend.Models.PresentationDetail", b =>
                {
                    b.HasOne("Cahut_Backend.Models.Presentation", "Presentation")
                        .WithMany("PresentationDetails")
                        .HasForeignKey("PresentationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Presentation");
                });

            modelBuilder.Entity("Cahut_Backend.Models.UserSubmitChoice", b =>
                {
                    b.HasOne("Cahut_Backend.Models.Group", "Group")
                        .WithMany("UserSubmitChoices")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Cahut_Backend.Models.MultipleChoiceOption", "MultipleChoiceOption")
                        .WithMany("UserSubmitChoices")
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Cahut_Backend.Models.MultipleChoiceQuestion", "MultipleChoiceQuestion")
                        .WithMany("UserSubmitChoices")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Cahut_Backend.Models.User", "User")
                        .WithMany("UserSubmitChoices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("MultipleChoiceOption");

                    b.Navigation("MultipleChoiceQuestion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cahut_Backend.Models.UserUpvoteQuestion", b =>
                {
                    b.HasOne("Cahut_Backend.Models.Group", "Group")
                        .WithMany("UserUpvoteQuestions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Cahut_Backend.Models.Presentation", "Presentation")
                        .WithMany("UserUpvoteQuestions")
                        .HasForeignKey("PresentationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Cahut_Backend.Models.PresentationQuestion", "PresentationQuestion")
                        .WithMany("UserUpvoteQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Cahut_Backend.Models.User", "User")
                        .WithMany("UserUpvoteQuestions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Presentation");

                    b.Navigation("PresentationQuestion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cahut_Backend.Models.MultipleChoiceQuestion", b =>
                {
                    b.HasOne("Cahut_Backend.Models.MultipleChoiceSlide", "MultipleChoiceSlide")
                        .WithMany("MultipleChoiceQuestions")
                        .HasForeignKey("SlideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MultipleChoiceSlide");
                });

            modelBuilder.Entity("Cahut_Backend.Models.PresentationQuestion", b =>
                {
                    b.HasOne("Cahut_Backend.Models.Presentation", "Presentation")
                        .WithMany("PresentationQuestions")
                        .HasForeignKey("PresentationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Presentation");
                });

            modelBuilder.Entity("Cahut_Backend.Models.HeadingSlide", b =>
                {
                    b.HasOne("Cahut_Backend.Models.Presentation", "Presentation")
                        .WithMany("HeadingSlides")
                        .HasForeignKey("PresentationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Presentation");
                });

            modelBuilder.Entity("Cahut_Backend.Models.MultipleChoiceSlide", b =>
                {
                    b.HasOne("Cahut_Backend.Models.Presentation", "Presentation")
                        .WithMany("MultipleChoiceSlides")
                        .HasForeignKey("PresentationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Presentation");
                });

            modelBuilder.Entity("Cahut_Backend.Models.ParagraphSlide", b =>
                {
                    b.HasOne("Cahut_Backend.Models.Presentation", "Presentation")
                        .WithMany("ParagraphSlides")
                        .HasForeignKey("PresentationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Presentation");
                });

            modelBuilder.Entity("Cahut_Backend.Models.Chat", b =>
                {
                    b.Navigation("ChatMessages");
                });

            modelBuilder.Entity("Cahut_Backend.Models.Group", b =>
                {
                    b.Navigation("GroupDetails");

                    b.Navigation("UserSubmitChoices");

                    b.Navigation("UserUpvoteQuestions");
                });

            modelBuilder.Entity("Cahut_Backend.Models.MultipleChoiceOption", b =>
                {
                    b.Navigation("UserSubmitChoices");
                });

            modelBuilder.Entity("Cahut_Backend.Models.Presentation", b =>
                {
                    b.Navigation("Chat")
                        .IsRequired();

                    b.Navigation("HeadingSlides");

                    b.Navigation("MultipleChoiceSlides");

                    b.Navigation("ParagraphSlides");

                    b.Navigation("PresentationDetails");

                    b.Navigation("PresentationQuestions");

                    b.Navigation("UserUpvoteQuestions");
                });

            modelBuilder.Entity("Cahut_Backend.Models.Role", b =>
                {
                    b.Navigation("GroupDetails");
                });

            modelBuilder.Entity("Cahut_Backend.Models.User", b =>
                {
                    b.Navigation("Group");

                    b.Navigation("Presentations");

                    b.Navigation("UserSubmitChoices");

                    b.Navigation("UserUpvoteQuestions");
                });

            modelBuilder.Entity("Cahut_Backend.Models.MultipleChoiceQuestion", b =>
                {
                    b.Navigation("MultipleChoiceOptions");

                    b.Navigation("UserSubmitChoices");
                });

            modelBuilder.Entity("Cahut_Backend.Models.PresentationQuestion", b =>
                {
                    b.Navigation("UserUpvoteQuestions");
                });

            modelBuilder.Entity("Cahut_Backend.Models.MultipleChoiceSlide", b =>
                {
                    b.Navigation("MultipleChoiceQuestions");
                });
#pragma warning restore 612, 618
        }
    }
}
